server:
  port: 8005
spring:
  application:
    name: easylife-gateway
  cloud:
    gateway:
#      filter:
#       - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedCredentials: true
            allowedHeaders:
              - X-Requested-With
              - Origin
              - Content-Type
              - Accept
              - Authorization
              - expired_date
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            exposedHeaders:
              - Authorization
              - expired_date


      routes:
        - id: mail-invitation
          uri: lb://adherent-service
          predicates:
            - Path=/activate/mail-invitation
            - Method=POST


        - id: verification
          uri: lb://adherent-service
          predicates:
            - Path=/activate/verification
            - Method=GET

        - id: login
          uri: lb://compte-service
          predicates:
            - Path=/login
            - Method=POST



        - id: createCompte
          uri: lb://compte-service
          predicates:
            - Path=/compte/createcompte
            - Method=POST

        - id: fordAdherent
          uri: lb://compte-service
          predicates:
            - Path=/compte/compteOfAdherent
            - Method=GET

        - id: updateSolde
          uri: lb://compte-service
          predicates:
            - Path=/compte/updateSolde
            - Method=PUT





      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
